# Generated by Django 4.2 on 2024-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='Profile Online mı?'),
        ),
    ]
