# Generated by Django 4.2 on 2024-01-03 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0002_profile_islogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Paket Adı')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('pre', models.BooleanField(default=False, verbose_name='Premium Pakedi')),
                ('spor', models.BooleanField(default=False, verbose_name='Spor Pakedi')),
                ('sinema', models.BooleanField(default=False, verbose_name='Sinema Pakedi')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='-', max_length=50, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, default='-', verbose_name='Adres')),
                ('packed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
