# Generated by Django 4.2 on 2024-01-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_remove_usermy_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermy',
            name='packed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi'),
        ),
    ]
