# Generated by Django 4.2 on 2024-01-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0003_packed_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='-', max_length=50, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, default='-', verbose_name='Adres')),
                ('packed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
