# Generated by Django 4.2 on 2024-01-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_usermy'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermy',
            name='user_active',
            field=models.CharField(default='123', max_length=50, verbose_name='Kullanıcı Doğrulama Linki'),
        ),
        migrations.AlterField(
            model_name='usermy',
            name='packed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi'),
        ),
    ]
