# Generated by Django 4.2 on 2024-01-08 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0006_alter_usermy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermy',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user2', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
